### ISSUE TITLE
Interested in using with Rails

### ISSUE THREAD

**Issue by chrisnicola** [rosenfeld/auto_reloader#1]
This is fairly easy to setup with Rails server using a middleware, however I can't find a good way to use it with the Rails console. Ideally, I'd like to hook into the `reload!` command. For now I've just extended my console with a `ar!` command that calls `AutoReload.reload!` unfortunately this seems to only unload things.

**Comment by rosenfeld** [comment]
Well, actually `reload!` is possibly not a good name as it actually will indeed only unload things so that they could be reloaded as needed. I'm using it with Rails too (while keeping `ActiveSupport::Dependencies` as well) but I'm not sure what exactly `reload!` does in the console. I thought it would basically call `ActiveSupport::Dependencies.clear`. AS::Dependencies supports autoloading, so you might think it's reloading just because you're not calling require after calling reload!, but you'll have to require your files again after calling `AutoReloader.reload!`.

**Comment by rosenfeld** [comment]
I should probably write some documentation explaining a few ways it can be used with Rails. Basically you can mount a rack app from the Rails router and it would share the same middlewares and session. But what I actually do for my own application is the opposite. I have a Roda app that will forward the request to Rails if it can't handle it. This way I have full control of which middlewares will be loaded for each request. But I can't reuse the Rails session, which is fine for my application.

**Comment by rosenfeld** [comment]
Do you think a new `default_reload_block` option would help you? If it was passed to `AutoReloader.activate` then it would be executed if no block was passed to `reload!`. Or we could instead make `activate` accept such block instead of a new option. This way you would be able to just call `reload!` and the default block would actually reload everything required in that block. What do you think?

**Comment by rosenfeld** [comment]
Anyway, I'd like to let you know that a middleware is not necessarily a requirement. Here's how you could set it up by modifying `config.ru`:

```ruby
require ::File.expand_path('../config/environment',  __FILE__)

if ENV['RACK_ENV'] != 'development'
  run MyApp::Application
else
  require 'auto_reloader'
  AutoReloader.activate reloadable_paths: ['my_app']
  run -> (env) {
    AutoReloader.reload! do
      MyApp::Application.call env
    end
  }
end
```

**Comment by chrisnicola** [comment]
Yeah I've set it up that way as well. Though I was getting errors where things were being unloaded that were still being referenced. I ended up just using `require_dependency` which seems to be working ok.

**Comment by rosenfeld** [comment]
I'm curious. Would you mind explaining it better? What kind of errors were you getting?

If you were using both ActiveSupport::Dependencies and AutoReloader to reload the same files then I guess it may not work very well with AutoReloader since it assumes the constant still exists while AS::Dependencies may have already removed it. It's probably a good idea to rescue NameError while trying to remove a constant anyway. I'll do that later once I'm back to home.

**Comment by rosenfeld** [comment]
I've just released 0.2.2 with a safe method for removing constants. If you think you're still facing issues, please let me know more details about it and I'll reopen the ticket.

**Comment by chrisnicola** [comment]
The specific error I'm getting I think is coming from my own code:

```

ArgumentError (A copy of API::InvestmentAccount::Details has been removed from the module tree but is still active!):
  lib/api/investment_account/details.rb:42:in `call'
  lib/api/investment_account/details.rb:31:in `call'
  app/controllers/investment_accounts_controller.rb:12:in `show'
  lib/rack/content_security_policy.rb:26:in `call'
  config.ru:15:in `block (3 levels) in <main>'
  config.ru:14:in `block (2 levels) in <main>'
```

**Comment by chrisnicola** [comment]
Ok I think I've got the setup. The following is required.

1. Add '/lib' folder to autoload_paths
2. Load `./lib` dependencies with `require_dependency` where they are used
3. Add middleware or `config.ru` wrapper to call `AutoReloader.reload!`.

Without step 1 and 2 it appears results are inconsistent with Rails. It was a bit of trial and error so I may still have some misunderstandings but this setup appears to work for Rails server. I'm going to do some more testing for the console runner.

**Comment by rosenfeld** [comment]
It seems your code is referencing an autoreloadable class which can indeed cause trouble no matter what reloader you use, but I can't know exactly how your code works to have a better understanding of it.

This topic might help you understanding:

http://stackoverflow.com/questions/29636334/a-copy-of-xxx-has-been-removed-from-the-module-tree-but-is-still-active

Basically, if you are referencing a reloadable class from a non-reloadable class you'll have problems. You should either leave API::InvestmentAccount::Details out of the reloadable code or make the code referencing it be also reloadable.

**Comment by rosenfeld** [comment]
I just saw your new comment. You don't need to add lib to autoload_paths necessarily if you use AutoReloader to reload that code, as long as AutoReloader.reload! is called before ActiveSupport::Dependencies.clear.

**Comment by rosenfeld** [comment]
I mean, instead of adding lib to autoload_paths you could add lib to reloadable_paths option in AutoReloader. This way you wouldn't have to use require_dependency in your source files under lib/.

**Comment by rosenfeld** [comment]
I suggest using it in config.ru like I demonstrated rather than as a middleware because it's simpler to be sure AutoReload.reload! will be called before ActiveSupport::Dependencies.clear.

**Comment by rosenfeld** [comment]
But if you are not using AutoReloader, than you're right. This is how I used to do in my Rails application before I decided to create AutoReloader. I also have many files under lib and they all use require_dependency. But this is going to change gradatively now that I'm moving the reloading code from AS::Dependencies to AutoReloader...

**Comment by chrisnicola** [comment]
So a couple of things. I am using config.ru and I don't see how using a middleware would change anything about how it gets called here.

Second: Using require_dependencies does not actually seem to ensure that /lib get unloaded and reloaded on changes. At least not that I have been able to get working with Rails. Everything in my /lib folder is written in a Gem style though and there is no autoloading or require_dependency, everything is just require. Perhaps that is why Rails doesn't unload it properly.

`AutoLoader` works for me with rails, but only if I use `require_dependency` to require the top level files from /lib when it rails. Inside /lib I only use `require`. I'm guessing this is because AutoLoader unloads the constants and the Rails attempts to resolve them again from /lib using it's `autoload_paths` functionality. The `require_dependency` part might be unnecessary now that I think of it.

**Comment by rosenfeld** [comment]
> So a couple of things. I am using config.ru though I don't see how using a middleware would change anything about how it gets called here.

If I remember correctly ActiveSupport::Dependencies.clear is called in one of the middlewares used by Rails. If you implement another middleware to call AutoReloader.reload! and use it after Rails own middleware, it means the constants will still exist when AS::Dependencies.clear is called. I'm not sure if that could cause any issues in other middlewares in between the Rails one and your own. So, if you make sure your own middleware loads before the Rails one calling AS::Dependencies.clear it should work fine. Otherwise it could lead to some bugs in corner cases I guess.

**Comment by chrisnicola** [comment]
I don't know, I did notice a lot of that code changed in Rails 5. For whatever reason in 4.2 using `require_dependencies` (without AutoReloader) does not work at all for me in terms of reloading code from /lib when I make changes. If it did I'd probably be happy to use it on it's own.

As for the middleware issue, as long is the `AutoReloader` middleware is first then it should have the exact same effect as `config.ru` but avoids having to actually pollute `config.ru` with what is really a development environment concern.

**Comment by rosenfeld** [comment]
>  Using require_dependency by itself in Rails does not actually seem to ensure that /lib constants get unloaded and reloaded when files change.

That's because Rails will simple require those files unless they are part of autoload_paths. I didn't say it was wrong to append lib to autoload_paths. I just said this is not a must if you are relying on AutoReloader for reloading your code and add lib to reloadable_paths as AutoReloader will figure out newly created top-level constants automatically when you call require on any reloadable path.

**Comment by rosenfeld** [comment]
> As for the middleware issue, as long is the AutoReloader middleware is first then it should have the exact same effect as config.ru but avoids having to actually pollute config.ru with what is really a development environment concern.

That's fine. In that case I'd conditionally add this middleware only for development mode and make sure it goes before Rails' own middleware responsible for calling ActiveSupport::Dependencies.clear.

**Comment by rosenfeld** [comment]
> Everything in my /lib folder is written in a Gem style though and there is no autoloading or require_dependency used in /lib, everything is just require. Perhaps this is why Rails doesn't unload it properly.

That's right. ActiveSupport::Dependencies requires you to always use require_dependency for code that should be reloaded. Whenever you call "require" it won't reload that file. If you don't call require but relies on its naming conventions then ActiveSupport::Dependencies will automatically load the proper files for you and your files would be reloaded.

**Comment by chrisnicola** [comment]
> That's right. ActiveSupport::Dependencies requires you to always use require_dependency for code that should be reloaded. 

So that is basically my problem. I don't want my /lib code polluted by any Rails-isms like `require_dependency` making that a non-starter for code reloading.

So essentially I have to use `AutoReloader` combined with `autoload_paths` to make this work with Rails. Which is fine for me for now. I really appreciate the work you've done on this, it has been really helpful for the work I'm doing right now.

So is there any reason why `AutoLoader` doesn't re-require the files it unloads when `reload!` is called? I'm guessing because file names can change, which makes sense I suppose, but you could just throw out any that are missing.

**Comment by chrisnicola** [comment]
I'd be interested in hearing more about how you are using Roda with Rails. We are currently looking into moving from Rails to Roda, hence the movement of our core domain logic into /lib.

**Comment by rosenfeld** [comment]
> So that is basically my problem. I don't want my /lib code polluted by any Rails-isms like require_dependency making that a non-starter for code reloading.

I feel about the same but I didn't have any options before I decided to create AutoReloader. Now I'll start moving out from require_dependency. Actually I'm moving out to Roda gradatively but one shouldn't have to leave Rails in order to be able to replace ActiveSupport::Dependencies with AutoReloader I guess. At least in theory. Maybe you'd have to require all your controllers in routes.rb since AutoReloader doesn't handle autoloading. Or implement your own autoloader or keep using AS::Dependencies altogether with AutoReloader.

**Comment by chrisnicola** [comment]
That sounds awesome. BTW this is the "module" I created to hook up Rails server and console.

https://gist.github.com/chrisnicola/f34a7cd80bfd3aa9b3d696bcd9b35d03

And in my `development.rb` I added:

```
  RailsAutoReloader.activate

  config.middleware.unshift RailsAutoReloader::Middleware

  console do
    # Add ar! method to call reload! and AutoReloader.reload!
    #http://blog.nhocki.com/2015/06/03/add-helper-methods-to-your-rails-console-with-pry/
    TOPLEVEL_BINDING.eval('self').extend RailsAutoReloader::Console
  end
```

Keep in mind the console bit is specific to `pry-rails`. I think with the default IRB console it is done a bit differently.

**Comment by rosenfeld** [comment]
My core logic has been in lib for a long while actually. Our application was never much tied to Rails, so moving it to something else is not much of an effort. The hardest part for us was to move from Sprockets to Webpack, but the motivation was not that I wanted to move from Rails. I was looking towards loading our front-end faster and Webpack allowed us to support lazy code loading in the client-side. Then I had to take lots of manual work to get rid of the js-routes gem dependency, which depends on Rails routes. The only missing bit I want to move away before switching to Roda is Devise unless I'm missing something. I would replace Devise anyway even if we would keep Rails because it doesn't support Sequel officially. So, basically, as I realize Rails isn't actually providing me any real goods, I think it makes more sense to move to a lightweight alternative such as Roda. And I'm really happy with Sequel which is also maintained by Jeremy Evans, so I'm inclined towards Roda because of him actually.

**Comment by rosenfeld** [comment]
> So essentially I have to use AutoReloader combined with autoload_paths to make this work with Rails. Which is fine for me for now.

I don't actually think you really need ActiveSupport::Dependencies (thus autoload_paths) if you are using AutoReloader and configure your app properly.

**Comment by chrisnicola** [comment]
Sounds pretty much the same as us. We've also moved from Sprockets to Webpack. Fortunately some example work had already been published for that so it didn't take me too long. We also, fortunately, did not use Devise in this project at the beginning.

As for the `autoload_paths`. I've tried it without and it doesn't work. It unloads the constants, but rails never reloads them unless I make a change to the files that declare the `require`'s. This is why I was suggesting that `AutoReloader` could handle reloading.

**Comment by rosenfeld** [comment]
> So is there any reason why AutoLoader doesn't re-require the files it unloads when reload! is called? 

The name is currently unfortunate. It doesn't actually reload anything it just unloads everything that was loaded since it was activated and that is reloadable. I think ActiveSupport::Dependencies.clear is a better name in that sense. `reload!` would only make sense if the API allowed a default block to be run after unloading the reloadable code. Currently the API doesn't support this but it could be added if we find that could be useful...

**Comment by rosenfeld** [comment]
> As for the autoload_paths. I've tried it without and it doesn't work. It unloads the constants, but rails never reloads them unless I make a change to the files that declare the require's. This is why I was suggesting that AutoReloader could handle reloading.

Your code is probably relying on AS::Dependencies autoloading features, which is not the case for my own code. So, if you just expect some constant to exist without requiring it and it works it's because it was autoloaded by ActiveSupport::Dependencies. This autoloading will only happen if the path is in autoload_paths, that's why it's called this way.

**Comment by rosenfeld** [comment]
With AutoReloader, you'll have to always explicitly require your dependencies, which is what I really want in my apps since I don't like autoloading.

**Comment by rosenfeld** [comment]
As for your RailsAutoReloader it should work. If it has some bug it's not obvious.

**Comment by rosenfeld** [comment]
> I'd be interested in hearing more about how you are using Roda with Rails. We are currently looking into moving from Rails to Roda, hence the movement of our core domain logic into /lib.

I'll probably write an article about this after I'm confortable with the new design I'm creating in the process of moving from Rails to Roda. I'll let you know once I publish it.

**Comment by rosenfeld** [comment]
If you want to improve your script you could simply call `unload!` rather than `reload! onchange: false`:

https://gist.github.com/chrisnicola/f34a7cd80bfd3aa9b3d696bcd9b35d03#file-rails_auto_reloader-rb-L23

**Comment by chrisnicola** [comment]
Yeah I was considering that. Thanks again. I'll let you know how things go.
